name: Main
on:
  - push
jobs:
  Test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install modules
        run: yarn install

      - name: Setup Aliyun CLI
        uses: ./
        with:
          aliyun-cli-version: '3.0.29'
          mode: AK
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          region: ${{ secrets.ALIYUN_REGION }}
